version: '3.8'


services:
  # --- PostgreSQL Database ---
  my-postgres:
    image: postgres:15-alpine
    container_name: hospital-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SpringBootHospitalManagementSystem_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d SpringBootHospitalManagementSystem_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  my-redis:
    image: redis:latest
    container_name: hospital-redis-container
    ports:
      - "6380:6379"  # <--- firstly "6379:6379" tha, ab bahar ka port 6380 kar diya

  my-rabbitmq:
    image: rabbitmq:3-management
    container_name: hospital-rabbitmq-container
    ports:
      - "5673:5672"     # Bahar ka main port 5672 se badal kar 5673 kar diya
      - "15673:15672"   # UI dashboard ka port 15672 se badal kar 15673 kar diya
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app-instance1:
    build: .
    image: hospital-app-1:latest
    container_name: hospital-app-1
    environment:
      - INSTANCE_NAME=hospital-app-1
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DOCKER_REDIS_HOST=my-redis
      - DOCKER_REDIS_PORT=6379                        # <--- Internal Docker network port
      - DOCKER_RABBIT_HOST=my-rabbitmq
      - DOCKER_RABBIT_PORT=5672
      - DB_HOST=my-postgres
      - DB_PORT=5432
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}          # <--- Docker ko Windows se key pass hogi
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}  # <--- Docker ko Windows se secret pass hoga
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}          # <--- GitHub Key
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}  # <--- GitHub Secret
    depends_on:
      my-postgres:
        condition: service_healthy                             # <--- UPDATED (Waits for DB)
      my-redis:
        condition: service_started
      my-rabbitmq:
        condition: service_healthy


  app-instance2:
    build: .
    image: hospital-app-2:latest
    container_name: hospital-app-2
    environment:
      - INSTANCE_NAME=hospital-app-2
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DOCKER_REDIS_HOST=my-redis
      - DOCKER_REDIS_PORT=6379
      - DOCKER_RABBIT_HOST=my-rabbitmq
      - DOCKER_RABBIT_PORT=5672
      - DB_HOST=my-postgres
      - DB_PORT=5432
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}          # <--- Docker ko Windows se key pass hogi
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}  # <--- Docker ko Windows se secret pass hoga
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}          # <--- GitHub Key
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}  # <--- GitHub Secret
    depends_on:
     my-postgres:
      condition: service_healthy                             # <--- UPDATED
     my-redis:
      condition: service_started
     my-rabbitmq:
      condition: service_healthy

  nginx-lb:
    image: nginx:latest
    container_name: hospital-nginx-lb
    ports:
      - "80:80"       # Bahar ki duniya ke liye main port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - app-instance1
        - app-instance2
  # --- Prometheus (Metrics Scraper) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: hospital-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # --- Grafana (Visual Dashboard) ---

  grafana:
    image: grafana/grafana:latest
    container_name: hospital-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data: