spring.application.name=HospitalManagement

# Database Config
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/SpringBootHospitalManagementSystem_db
spring.datasource.username=postgres
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Production Safe JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
spring.jpa.defer-datasource-initialization=true
spring.jpa.init.mode=always



# *************
## --- REAL GMAIL SMTP CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=WARN


#SpringSecurity --> SecretKey
# Agar system environment me JWT_SECRET_KEY mile toh wo use hoga,
jwt.secretKey=${JWT_SECRET_KEY}


#Redis Caching
spring.cache.type=redis
spring.data.redis.host=${DOCKER_REDIS_HOST:localhost}
spring.data.redis.port=${DOCKER_REDIS_PORT:6379}
logging.level.org.springframework.cache=TRACE


#Rebbit-MQ Message Broker
spring.rabbitmq.host=${DOCKER_RABBIT_HOST:localhost}
spring.rabbitmq.port=${SPRING_DATA_RABBIT_PORT:5672}
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest


#Virtual Thread -->
spring.threads.virtual.enabled=true
spring.datasource.hikari.maximum-pool-size=10


server.port=8080
instance.name=${INSTANCE_NAME:default-instance}


# ==========================================
# OAuth2 Social Login Configuration (Google & GitHub)
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}


spring.output.ansi.enabled=ALWAYS

#Swagger config
springdoc.swagger-ui.path=/doc

# Swagger UI Styling & Compact Layout
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.enable-filter=true

# Load Balancer / Reverse Proxy Support (Important!)
# Isse Swagger samajhta hai ki request Nginx/Load Balancer ke zariye aa rahi hai
server.forward-headers-strategy=framework
server.servlet.session.timeout=1m

