spring.application.name=HospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBootHospitalManagementSystem_db
spring.datasource.username=postgres
spring.datasource.password=yash3035

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

#server.tomcat.threads.max=500

spring.jpa.defer-datasource-initialization=true
spring.jpa.init.mode=always
spring.jpa.init.data.locations=classpath:data.sql


# *************
#/// ---> Mail trap ki application.properties
# --> Mailtrap Credentials
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=fb7f46bb615bb2
#spring.mail.password=b9df6790552d81
#
## ---> SMTP Auth & TLS (Handshake settings)
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



# *************
# --- REAL GMAIL SMTP CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashjadhav4883@gmail.com
# Jo 16-digit code mila hai, use bina spaces ke yahan likho
spring.mail.password=ioza lxrw pqqi fpvc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email Debugging (Taki console mein dikhe kya ho raha hai)
logging.level.org.springframework.mail=DEBUG
#ioza lxrw pqqi fpvc


## Spring Security Related Properties
#spring.security.user.name=yash
#spring.security.user.password=yash3035

#SpringSecurity --> SecretKey
jwt.secretKey = "MySecretKeyNJeffEufFie73899ks09387fnMySecretKey12"

# caching
#spring.cache.type=simple
#logging.level.org.springframework.cache=TRACE

#Redis Caching
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.org.springframework.cache=TRACE