spring.application.name=HospitalManagement

#spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBootHospitalManagementSystem_db
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/SpringBootHospitalManagementSystem_db
spring.datasource.username=postgres
spring.datasource.password=yash3035

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

#server.tomcat.threads.max=500

spring.jpa.defer-datasource-initialization=true
spring.jpa.init.mode=always
spring.jpa.init.data.locations=classpath:data.sql


# *************
#/// ---> Mail trap ki application.properties
# --> Mailtrap Credentials
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=fb7f46bb615bb2
#spring.mail.password=b9df6790552d81
#
## ---> SMTP Auth & TLS (Handshake settings)
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



# *************
## --- REAL GMAIL SMTP CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashjadhav4883@gmail.com
# Jo 16-digit code mila hai, use bina spaces ke yahan likho
spring.mail.password=ioza lxrw pqqi fpvc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email Debugging (Taki console mein dikhe kya ho raha hai)
logging.level.org.springframework.mail=DEBUG
##ioza lxrw pqqi fpvc


## Spring Security Related Properties
#spring.security.user.name=yash
#spring.security.user.password=yash3035

#SpringSecurity --> SecretKey
jwt.secretKey = "MySecretKeyNJeffEufFie73899ks09387fnMySecretKey12"

# caching
#spring.cache.type=simple
#logging.level.org.springframework.cache=TRACE

#Redis Caching
spring.cache.type=redis
# Agar DOCKER_REDIS_HOST mile toh wo use karega, nahi toh default localhost
#spring.data.redis.host = ${DOCKER_REDIS_HOST:localhost}
#spring.data.redis.host=my-redis

# <--- Isko 6379 se badal kar 6380 kar do
spring.data.redis.host=${DOCKER_REDIS_HOST:localhost}
spring.data.redis.port=${DOCKER_REDIS_PORT:6380}


#spring.data.redis.port=6379
logging.level.org.springframework.cache=TRACE


#Rebbit-MQ Message Broker
# Agar DOCKER_RABBIT_HOST mile toh wo use karega, nahi toh default localhost
#spring.rabbitmq.host=${DOCKER_RABBIT_HOST:localhost}

#spring.rabbitmq.host = localhost

# Isko 5672 se badal kar 5673 kar do
spring.rabbitmq.host=${DOCKER_RABBIT_HOST:localhost}
spring.rabbitmq.port=${SPRING_DATA_RABBIT_PORT:5672}
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest


#Virtual Thread -->
spring.threads.virtual.enabled=true


spring.datasource.hikari.maximum-pool-size=10

server.forward-headers-strategy=framework

server.port=8080
instance.name=${INSTANCE_NAME:default-instance}


# ==========================================
# OAuth2 Social Login Configuration (Google & GitHub)
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
